### PR TITLE
Allow specific node styles for each node

### PR DESCRIPTION
**Pull request by facontidavide**
Hi,
I have an application in which I want to customize individually the style of each node.
This PR allows that without changing the default behavior.

### CODE REVIEW

**Comment by paceholder** [comment]
Wouldnt' it be better to return a custom style from the model?
For example, as QString or JSON. 
An empty custom style would mean that the default one should be applied

**Comment by russelltg** [comment]
No, I think this way is better because then you loose the flexibility of
changing the style of just one node, and can only change the style of all
nodes of one type. For example, like if a user "bookmarked" a node, you'd
probably want to change the style of that one node, but not all nodes of
the same type.

**Comment by paceholder** [comment]
You would still be able to change the style of one node even if the style data is stored in the model.

The style initialization would work in three stages:
1. Set global NodeStyle as in the `styles` example (or use default global style by doing nothing).
2. [optionally] In the Model constructor set "specific" model-defined Node style
3. [optionally] Modify model style depending on the model/node state 

The style usage would also work in two stages:
1. Check if the model possesses a specific style
2. If not, use global style from `StyleCollection::nodeStyle`

With the initially proposed approach it wouldn't be impossible to define a model-default style

**Comment by facontidavide** [comment]
> With the initially proposed approach it wouldn't be possible to define a model-default style

Good point.
it looks weird to include some graphic style into de DataModel, but pragmatically speaking it would do what I want.

**Comment by russelltg** [comment]
> You would still be able to change the style of one node even if the style data is stored in the model.

Right of course. Wasn't thinking about it right :).

**Comment by facontidavide** [comment]
Alright, I applied the changes and rebased the branch. Take a look

**Comment by paceholder** [comment]
Merged manually with tiny code style fixes.

**Comment by paceholder** [comment]
> it looks weird to include some graphic style into de DataModel,

On one hand yes, it looks weird.

But on other hand, Qt does almost the same with 
`QVariant QAbstractItemModel::data(const QModelIndex &index, int role = Qt::DisplayRole) const`

There we can return QIcon for any abstract-item-based widget using the role == Qt::DecorationRole.

**Pull request closed without merging**
