### PR TITLE
Support inclusion of FlowView via Qt Designer

### PR DESCRIPTION
**Pull request by ypnos**
To be able to fit this widget in the typical .ui file workflow, we need to be able to construct it with a parent widget and set the scene after UI setup.

### CODE REVIEW

**Comment by ypnos** [comment]
Please note that although this is two commits they are not independent of each other, I just wanted to highlight the different changes. The introduction of `init()` is to stay compatible with C++03. Personally I would prefer to use a delegating constructor.

**Comment by paceholder** [comment]
Thanks for the pull-request.

I think there is no need to stick to C++03 standard. The code base uses C++14 in the CMakeLists.txt and is being build with C++11 compilers in continuous integration.

Could you update it with the delegating constructors? Thanks

Dmitry

**Comment by paceholder** [comment]
Could you replace `init()` with a delegating constructor?

**Comment by ypnos** [comment]
Sorry for the delay, I am on it!

**Comment by paceholder** [comment]
No problem, I was just pinging :)

**Pull request merged**
