### PR TITLE
Simplifying cmake

### PR DESCRIPTION
**Pull request by QianMoth**
Every time I add or delete a file I forget to change cmake, change it to this and there will be no problem.

### CODE REVIEW

**Comment by paceholder** [comment]
The explicit listing of files has been done on purpose
https://github.com/paceholder/nodeeditor/pull/142

Besides, your proposed changes with the variable `${QT_VERSION_MAJOR}` does not work for some reason. I do not know whether  it depends on cmake, OS or Qt version. In my case (Qt 6.4, MacOS, cmake 3.25) the variable remains empty after finding the Qt libs.

**Comment by QianMoth** [comment]
Thank you for your reply

**Comment by QianMoth** [comment]
But there is macos qt5.15.2 in the github ci and the compilation passes

**Comment by paceholder** [comment]
You are right, let me pull you branch to my computer and see what exactly happens

**Comment by paceholder** [comment]
Opps looks like you removed your branch completely

**Comment by QianMoth** [comment]
> Opps looks like you removed your branch completely

i restore it

**Comment by QianMoth** [comment]
Hi @paceholder , One more thing that needs to be fixed , Now in cmake you use `FATAL_ERRROR` with the extra letter `R`

**Comment by paceholder** [comment]
Sorry for closing this PR immediately, I see that your changes work now. Dunno what was wrong with my attempts before.

Please have a look: https://github.com/paceholder/nodeeditor/pull/355
I took all your proposed changes, move an MSVC flag and kept the whole list of files

**Pull request closed without merging**
