### PR TITLE
Enable custom Node connections

### PR DESCRIPTION
**Pull request by dine-j**
Hi!

I'm working on a project and would like to have more flexibility with Connections styles. I've added a few classes that should enable that, very much inspired by the work done for Nodes.

Let me know what you think.

### CODE REVIEW

**Comment by paceholder** [comment]
I was thinking along these lines, let met pull your code and look through it carefully.

Thanks for ther PR!

**Comment by xiaoxiao-zhou-q** [comment]
First of all, thank you for sharing!

I have seen this project, and I have an idea about how to make a group of processes (connected) realize Thread pool when the internal algorithm of some nodes takes a long time. The purpose is to optimize the overall time, and the second is to ensure that the Home screen is not stuck normally
Tencent QQ:  316995834

**Comment by nolankramer** [comment]
This change looks great, is there any additional feedback for the PR author? Or can it be merged?

**Comment by paceholder** [comment]
merged in https://github.com/paceholder/nodeeditor/pull/437 with some minor improvements. Thanks

**Pull request closed without merging**
