### PR TITLE
Fix vcpkg conflict and add documentation

### LINKED ISSUE #321: Unable to build when using `vcpkg` toolchain
The `vcpkg` toolchain causes infinite recursion.
```
[main] Building folder: nodeeditor 
[main] Configuring folder: nodeeditor 
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug "-DCMAKE_C_COMPILER:FILEPATH=C:\Program Files\LLVM\bin\clang.exe" "-DCMAKE_CXX_COMPILER:FILEPATH=C:\Program Files\LLVM\bin\clang++.exe" -Sd:/nodeeditor -Bd:/nodeeditor/build -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] CMake Error at D:/vcpkg/scripts/buildsystems/vcpkg.cmake:746 (set):
[cmake]   Maximum recursion depth of 100 exceeded
[cmake] Call Stack (most recent call first):
[cmake]   D:/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
...
[cmake]   D:/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "D:/nodeeditor/build/CMakeFiles/CMakeOutput.log".
[cmake]   D:/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
...
[cmake]   D:/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
[cmake]   external/CMakeLists.txt:11 (_find_package)
[cmake]   CMakeLists.txt:47 (find_package)
```

You have `vcpkg` installed and configured, and `qtbase` installed through `vcpkg`. Then you try to configure the repository with the following argument in the CMake command
```
cmake -B<builddir> -S<sourcedir> -DCMAKE_TOOLCHAIN_FILE=/path/to/vcpkg/scripts/buildsystems/vcpkg.cmake
```

The issue is met on a branch [v3alpha](https://github.com/paceholder/nodeeditor/tree/v3alpha)

### PR DESCRIPTION
**Pull request by arsdever**
Resolves #321

### CODE REVIEW

**Comment by arsdever** [comment]
I need someone to test this without `vcpkg`.

**Comment by paceholder** [comment]
Thanks for your pull request. Unfortunately, it broke the build.
I tried to fix it based on your changes. Waiting for the build results now...
https://github.com/paceholder/nodeeditor/pull/329

**Comment by arsdever** [comment]
@paceholder Hi. I was also trying to look through the PR again. I found something strange and wanted to clarify. On line [`external/CMakeLists.txt:2`](https://github.com/paceholder/nodeeditor/blob/master/external/CMakeLists.txt#L2) you require a version `2.13.7` for the `Catch2` package, but on this [`test/CMakeLists.txt:1`](https://github.com/paceholder/nodeeditor/blob/master/test/CMakeLists.txt#L1) line you require a version `2.3.0` for the same package. Is there a reason for that?

Anyways, with the following patch applied, it works fine with the `CMake`'s configuration command
when the `-DCMAKE_TOOLCHAIN_FILE=$VCPKG_DIR/scripts/buildsystems/vcpkg.cmake` flag is passed.

```diff
diff --git a/external/CMakeLists.txt b/external/CMakeLists.txt
index 49ee9d2..d7fbfcc 100644
--- a/external/CMakeLists.txt
+++ b/external/CMakeLists.txt
@@ -1,15 +1,7 @@
 if(BUILD_TESTING)
-  find_package(Catch2 2.13.7 QUIET)
+  find_package(Catch2 QUIET)

   if(NOT Catch2_FOUND)
     add_subdirectory(Catch2)
   endif()
 endif()
-
-if(NOT COMMAND find_package)
-  macro(find_package pkg)
-    if(NOT TARGET "${pkg}")
-      _find_package(${ARGV})
-    endif()
-  endmacro()
-endif()
diff --git a/test/CMakeLists.txt b/test/CMakeLists.txt
index dffa83b..6ee51b2 100644
--- a/test/CMakeLists.txt
+++ b/test/CMakeLists.txt
@@ -1,4 +1,4 @@
-find_package(Catch2 2.3.0 REQUIRED)
+find_package(Catch2 REQUIRED)

 if (Qt6_FOUND)
   find_package(Qt6 COMPONENTS Test)
```

**Comment by paceholder** [comment]
This part of the code wasn't originally written by me. That's why I can't give a detailed explanation.
I think after some fixes and modernization one version was updated and the other one left untouched.

**Comment by paceholder** [comment]
I merged my corrected branch. Thanks for your idea and let me know if something pops up again.

**Pull request closed without merging**
